version: '3.1'

services:
  app:
    build: 
      context: .
      dockerfile: ./php.dockerfile
    ports:
      - 80:80
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - 3306:3306
    volumes:
      - ./801.sql:/root/801.sql
    environment:
      MYSQL_ROOT_PASSWORD: 82!2v278MLPrUdd0h!T4
      MYSQL_ROOT_DATABASE: 801

  # Após a inicialização dos containers, execute os seguintes comandos:
  # docker compose exec db bash
  # mysql --user=root --password=$MYSQL_ROOT_PASSWORD -e "create database \`801\`;"
  # exit

  # mysql --user=root --password=$MYSQL_ROOT_PASSWORD 801 < /root/801.sql
